<?php

/**
 * Empleado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Empleado extends BaseEmpleado
{
	function getTipos($id=null,$nombre=null){
		$query = Doctrine_Query::create()
			->select('*')
			->from('tipoEmpleado');
		$bool = true;
		if($id!=null){
			if($bool == true){
				$query->where('id = ?',$id);
				$bool = false;
			}else{
				$query->andwhere('id = ?',$id);
			}
		}
		if($nombre!=null){
			if($bool==true){
				$query->where('nombre = ?',$nombre);
				$bool = false;
			}else{
				$query->andwhere('nombre = ?',$nombre);
			}
		}
		$query = $query->execute()->toArray();
		if(count($query)<=0){
			return 'error';
		}else{
			return $query;
		}
	}

	function getEmpleados($id=null,$id_user=null,$nombre=null,$rif=null,$id_tipo=null){
		$query = Doctrine_Query::create()
			->select('*')
			->from('empleado');
		$bool = true;
		if($id!=null){
			if($bool==true){
				$query->where('id = ?',$id);
				$bool = false;
			}else{
				$query->andwhere('id = ?',$id);
			}
		}
		if($id_user!=null){
			if($bool==true){
				$query->where('id_user = ?',$id_user);
				$bool = false;
			}else{
				$query->andwhere('id_user = ?',$id_user);
			}
		}
		if($nombre!=null){
			if($bool==true){
				$query->where('nombre = ?',$nombre);
				$bool = false;
			}else{
				$query->andwhere('nombre = ?',$nombre);
			}
		}
		if($rif!=null){
			if($bool==true){
				$query->where('rif = ?',$rif);
				$bool = false;
			}else{
				$query->andwhere('rif = ?',$rif);
			}
		}
		if($id_tipo!=null){
			if($bool==true){
				$query->where('id_tipo = ?',$id_tipo);
				$bool = false;
			}else{
				$query->andwhere('id_tipo = ?',$id_tipo);
			}
		}
		$query = $query->execute()->toArray();
		if(count($query)<=0){
			return 'no hay datos que retornar';
		}else{
			return $query;
		}
	}

}