<?php

/**
 * Log
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Log extends BaseLog
{
	public function Count($id=null, $iduser = null, $IP = null, $MAC = null, $idlogtype = null, $fecha = null, $inactivo = null){
		$count = 0;
		$q = Doctrine_Query::create() -> select('id') -> from('Log');
		if ($id != null) {
			if ($count == 0) {
				$q -> where('id = ?', $id);
				$count++;
			} else
				$q -> andwhere('id = ?', $id);
		}
		if ($iduser!= null) {
			if ($count == 0) {
				$q -> where('iduser = ?', $iduser);
				$count++;
			} else
				$q -> andwhere('iduser = ?', $iduser);
		}
		if ($IP != null) {
			if ($count == 0) {
				$q -> where('IP = ?', $IP);
				$count++;
			} else
				$q -> andwhere('IP = ?', $IP);
		}
		if ($MAC != null) {
			if ($count == 0) {
				$q -> where('MAC = ?', $MAC);
				$count++;
			} else
				$q -> andwhere('MAC = ?', $MAC);
		}
		if ($idlogtype != null) {
			if ($count == 0) {
				$q -> where('idlogtype = ?', $idlogtype);
				$count++;
			} else
				$q -> andwhere('idlogtype = ?', $idlogtype);
		}
		if ($fecha != null) {
			if ($count == 0) {
				$q -> where('fecha = ?', $fecha);
				$count++;
			} else
				$q -> andwhere('fecha = ?', $fecha);
		}
		if ($inactivo != null) {
			if ($count == 0) {
				$q -> where('inactivo = ?', $inactivo);
				$count++;
			} else
				$q -> andwhere('inactivo = ?', $inactivo);
		}
		$qArray = $q -> execute() -> toArray();
		return count($qArray);
	}

	public function MaxFecha($id=null, $iduser = null, $IP = null, $MAC = null, $idlogtype = null, $fecha = null, $inactivo = null){
		$count = 0;
		$q = Doctrine_Query::create() -> select('MAX(fecha)') -> from('Log');
		if ($id != null) {
			if ($count == 0) {
				$q -> where('id = ?', $id);
				$count++;
			} else
				$q -> andwhere('id = ?', $id);
		}
		if ($iduser!= null) {
			if ($count == 0) {
				$q -> where('iduser = ?', $iduser);
				$count++;
			} else
				$q -> andwhere('iduser = ?', $iduser);
		}
		if ($IP != null) {
			if ($count == 0) {
				$q -> where('IP = ?', $IP);
				$count++;
			} else
				$q -> andwhere('IP = ?', $IP);
		}
		if ($MAC != null) {
			if ($count == 0) {
				$q -> where('MAC = ?', $MAC);
				$count++;
			} else
				$q -> andwhere('MAC = ?', $MAC);
		}
		if ($idlogtype != null) {
			if ($count == 0) {
				$q -> where('idlogtype = ?', $idlogtype);
				$count++;
			} else
				$q -> andwhere('idlogtype = ?', $idlogtype);
		}
		if ($fecha != null) {
			if ($count == 0) {
				$q -> where('fecha = ?', $fecha);
				$count++;
			} else
				$q -> andwhere('fecha = ?', $fecha);
		}
		if ($inactivo != null) {
			if ($count == 0) {
				$q -> where('inactivo = ?', $inactivo);
				$count++;
			} else
				$q -> andwhere('inactivo = ?', $inactivo);
		}
		$qArray = $q -> execute() -> toArray();
		return $qArray;
	}
}