<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class User extends BaseUser
{
	public function getUsers($id=null,$email=null,$location_id=null,$role_id=null,$status=null,$validation_code=null,$paginaActual=null,$porPagina=null)
	{
		require_once 'phputils/mysqlConexion.php';	
		$handler = new pagination_handler();
		if ($porPagina == null){
			$porPagina = $handler -> porPagina;
		}
		$count = 0;
		$q = Doctrine_Query::create() -> select('u.id, r.id') -> from('User u, u.Role r');
		if ($id != null) {
			if ($count == 0) {
				$q -> where('u.id = ?', $id);
				$count++;
			} else
				$q -> andwhere('u.id = ?', $id);
		}
		if ($email != null) {
			if ($count == 0) {
				$q -> where('u.email = ?', $email);
				$count++;
			} else
				$q -> andwhere('u.email = ?', $email);
		}
		if ($location_id != null) {
			if ($count == 0) {
				$q -> where('u.location_id = ?', $location_id);
				$count++;
			} else
				$q -> andwhere('u.location_id = ?', $location_id);
		}
		if ($role_id != null) {
			if ($count == 0) {
				$q -> where('u.role_id = ?', $role_id);
				$count++;
			} else
				$q -> andwhere('u.role_id = ?', $role_id);
		}
		if ($status != null) {
			if ($count == 0) {
				$q -> where('u.status = ?', $status);
				$count++;
			} else
				$q -> andwhere('u.status = ?', $status);
		}
		if ($valitadion_code != null) {
			if ($count == 0) {
				$q -> where('u.validation_code = ?', $validation_code);
				$count++;
			} else
				$q -> andwhere('u.validation_code = ?', $validation_code);
		}
		if ($paginaActual != null) {
			$q -> offset($porPagina * ($paginaActual - 1));
			$q -> limit($porPagina);
		}
		$q->orderBy('u.id');
		$qArray = array();
		$qArray = $q -> execute() -> toArray();
		return $qArray;
	}
}