Articulos:
  connection: villadel_villa
  tableName: articulos
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    codigo:
      type: string(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    descripcion:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    alto:
      type: float(18)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ancho:
      type: float(18)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    largo:
      type: float(18)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    diametro:
      type: float(18)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    peso:
      type: float(18)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    empaque:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: false
      autoincrement: false
    fechaingreso:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    agotado:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    inactivo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    categoria:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tipo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Categorias:
      local: categoria
      foreign: id
      type: one
    Tipos:
      local: tipo
      foreign: id
      type: one
    FotosArt:
      local: id
      foreign: id_art
      type: many
    PrecioArt:
      local: id
      foreign: id_art
      type: many
    ArticulosIndex:
      local: id
      foreign: id
      type: many
Categorias:
  connection: villadel_villa
  tableName: categorias
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inactivo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  relations:
    Articulos:
      local: id
      foreign: categoria
      type: many
    Tipos:
      local: id
      foreign: id_cat
      type: many
Cliente:
  connection: villadel_villa
  tableName: cliente
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre:
      type: string(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    rif:
      type: string(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    direccion:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_tipo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    telefono:
      type: string(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inactivo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
Fotos:
  connection: villadel_villa
  tableName: fotos
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    descripcion:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    direccion:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inactivo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  relations:
    FotosArt:
      local: id
      foreign: id_foto
      type: many
FotosArt:
  connection: villadel_villa
  tableName: fotos_art
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_art:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_foto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    prioridad:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '-1'
      notnull: true
      autoincrement: false
    inactivo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  relations:
    Articulos:
      local: id_art
      foreign: id
      type: one
    Fotos:
      local: id_foto
      foreign: id
      type: one
Location:
  connection: villadel_villa
  tableName: location
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    User:
      local: id
      foreign: location_id
      type: many
Log:
  connection: villadel_villa
  tableName: log
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    iduser:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    ip:
      type: string(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    mac:
      type: string(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    idlogtype:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inactivo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  relations:
    LogType:
      local: idlogtype
      foreign: id
      type: one
    User:
      local: iduser
      foreign: id
      type: one
LogType:
  connection: villadel_villa
  tableName: log_type
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Log:
      local: id
      foreign: idlogtype
      type: many
PrecioArt:
  connection: villadel_villa
  tableName: precio_art
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_art:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_precio:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_tipo_cliente:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inactivo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  relations:
    Articulos:
      local: id_art
      foreign: id
      type: one
    Precios:
      local: id_precio
      foreign: id
      type: one
    TipoCliente:
      local: id_tipo_cliente
      foreign: id
      type: one
Precios:
  connection: villadel_villa
  tableName: precios
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    precio:
      type: float(18)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inactivo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  relations:
    PrecioArt:
      local: id
      foreign: id_precio
      type: many
Role:
  connection: villadel_villa
  tableName: role
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(15)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    User:
      local: id
      foreign: role_id
      type: many
TipoCliente:
  connection: villadel_villa
  tableName: tipo_cliente
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inactivo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  relations:
    PrecioArt:
      local: id
      foreign: id_tipo_cliente
      type: many
Tipos:
  connection: villadel_villa
  tableName: tipos
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_cat:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inactivo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
  relations:
    Categorias:
      local: id_cat
      foreign: id
      type: one
    Articulos:
      local: id
      foreign: tipo
      type: many
User:
  connection: villadel_villa
  tableName: user
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(205)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    location_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    role_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    status:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      default: valid
      notnull: true
      autoincrement: false
    validation_code:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Location:
      local: location_id
      foreign: id
      type: one
    Role:
      local: role_id
      foreign: id
      type: one
    Log:
      local: id
      foreign: iduser
      type: many
Vendedor:
  connection: villadel_villa
  tableName: vendedor
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_tipo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inactivo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
